# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 250)
        MainWindow.setMinimumSize(QtCore.QSize(250, 250))
        MainWindow.setMaximumSize(QtCore.QSize(250, 250))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(70, 130, 101, 21))
        self.button_save.setObjectName("button_save")
        self.label_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(81, 81, 101, 16))
        self.label_age.setObjectName("label_age")
        self.label_feedback = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_feedback.setGeometry(QtCore.QRect(70, 150, 111, 21))
        self.label_feedback.setObjectName("label_feedback")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 50, 112, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(parent=self.widget)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.input_name = QtWidgets.QLineEdit(parent=self.widget)
        self.input_name.setObjectName("input_name")
        self.horizontalLayout.addWidget(self.input_name)
        self.radio_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_jane.setGeometry(QtCore.QRect(81, 95, 71, 16))
        self.radio_jane.setObjectName("radio_jane")
        self.button_group = QtWidgets.QButtonGroup(MainWindow)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.radio_jane)
        self.radio_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_john.setGeometry(QtCore.QRect(81, 113, 81, 16))
        self.radio_john.setObjectName("radio_john")
        self.button_group.addButton(self.radio_john)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.button_save.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.label_age.setText(_translate("MainWindow", "CANDIDATES"))
        self.label_feedback.setText(_translate("MainWindow", "Please fill out all values"))
        self.label_name.setText(_translate("MainWindow", "ID"))
        self.radio_jane.setText(_translate("MainWindow", "Jane"))
        self.radio_john.setText(_translate("MainWindow", "John"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
